name = "nature-daily"
main = "src/index.ts"
compatibility_date = "2024-10-18"

[triggers]
crons = ["0 22 * * *"]

[vars]
FRONTEND_ORIGIN = "https://baxink.github.io"
AI_MODEL = "@cf/meta/llama-3.1-8b-instruct-fast"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "nature-daily-db"
database_id = "222ce2f9-d92f-493d-b80e-4986de5a0be0"
